export interface TBLShamelShatebPunishmentRequest {
    pageIndex?: number,
    rowInPage?: number,
    id?: number,
    serial?: number,
    healthnosalary_name?: string,
    duration?: number,
    documenttype_id?: number,
    documentnum?: string,
    documentdate_From?: string,
    documentdate_To?: string,
    salary?: number,
    amount?: number,
    eisalnum?: string,
    eisaldate_From?: string,
    eisaldate_To?: string,
    year_id?: number,
    month_id?: number,
    tax_status?: number,
    fname?: string,
    lname?: string,
    father?: string,
    accounter_id?: number
}
